In [5]:
#Q#1
import numpy as np

a = np.arange(0, 10).reshape((2, 5))
a[0] = -a[0]
print(a)


[[ 0 -1 -2 -3 -4]
 [ 5  6  7  8  9]]


In [9]:
#Q#2
import numpy as np

array = np.random.randint(1, 101, size=(5, 5))

avg = np.average(a)
min = np.min(a)
max = np.max(a)

row_sums = np.sum(array, axis=1)
column_sums = np.sum(array, axis=0)
print("Array of Random:\n", array)

print("Minimum Value:", min)
print("Maximum Value:", max)
print("Row sums:", row_sums)
print("Column sums:", column_sums)

Array of Random:
 [[87 44 86 76 66]
 [13 73 84 59 86]
 [18 91 40 61 88]
 [73 91 80  2 45]
 [41 43  7 45 48]]
Minimum Value: -4
Maximum Value: 9
Row sums: [359 315 298 291 184]
Column sums: [232 342 297 243 333]


In [10]:
#Q#3
import numpy as np

m1 = np.random.rand(3, 3)
m2 = np.random.rand(3, 3)

a = m1 + m2
s = m1 - m2
m = m1 * m2
d = m1 / m2

dot_product = np.dot(m1, m2)

print("Matrix 1:\n", m1)
print("Matrix 2:\n", m2)
print("Addition:\n", a)
print("Subtraction:\n", s)
print("Multiplication:\n", m)
print(" Division:\n", d)
print("Dot Product:\n", dot_product)


Matrix 1:
 [[0.77918473 0.17342204 0.15927209]
 [0.34064075 0.63755419 0.20583309]
 [0.60959785 0.11610314 0.51985436]]
Matrix 2:
 [[0.05817367 0.6169844  0.05008007]
 [0.00376288 0.20264214 0.64351778]
 [0.97887539 0.33990471 0.37373034]]
Addition:
 [[0.8373584  0.79040644 0.20935216]
 [0.34440363 0.84019633 0.84935087]
 [1.58847324 0.45600786 0.8935847 ]]
Subtraction:
 [[ 0.72101106 -0.44356236  0.10919203]
 [ 0.33687787  0.43491205 -0.43768469]
 [-0.36927754 -0.22380157  0.14612402]]
Multiplication:
 [[0.04532803 0.10699869 0.00797636]
 [0.00128179 0.12919534 0.13245725]
 [0.59672033 0.03946401 0.19428535]]
 Division:
 [[13.39411341  0.28108011  3.18034902]
 [90.52659617  3.14620736  0.31985611]
 [ 0.62275327  0.34157556  1.39098785]]
Dot Product:
 [[0.20188813 0.57002477 0.2101466 ]
 [0.22370031 0.40932901 0.50426284]
 [0.54477207 0.5763407  0.29952849]]


In [15]:
#Q#4
import numpy as np

array = np.random.randint(1, 101, size=(4, 4))

second_row = array[1]

third_column = array[:, 2]

sub_array = array[1:4, 0:3]

print("original array :\n", array)
print("second_row :\n", second_row)
print("third_column :\n", third_column)
print("sub_array:\n", sub_array)


original array :
 [[85 33 13 93]
 [36 39 30  7]
 [84 48 78 36]
 [30 24 71 92]]
second_row :
 [36 39 30  7]
third_column :
 [13 30 78 71]
sub_array:
 [[36 39 30]
 [84 48 78]
 [30 24 71]]


In [17]:
#Q#5

import numpy as np

array = np.arange(1, 21)
print("original array :\n", array)
filtered_elements = []

for i in range(len(array)):
    if array[i] % 2 == 0:
        array[i] = array[i] ** 2
    if array[i] > 50:
       filtered_elements.append(array[i])

print("Modified for even square Array:\n", array)
print("Elements greater than 50:\n", filtered_elements)

original array :
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Modified for even square Array:
 [  1   4   3  16   5  36   7  64   9 100  11 144  13 196  15 256  17 324
  19 400]
Elements greater than 50:
 [64, 100, 144, 196, 256, 324, 400]


In [29]:
#Q#6

import pandas as pd

data={
    'Name':['Hafsa','Ayesha','ahmed','Malaika','noor'],
    'Age':[12,23,34,34,21],
    'Gender':['female','female','male','female','female'],
    'Score':[12,23,34,34,21]
}

df = pd.DataFrame(data)
print("Data:")
print(df)

print("First few rows of the DataFrame:")
print(df.head())

# Inspect the data types of each column
print("\nData types of each column:")
print(df.dtypes)

# Get a summary of the DataFrame’s statistical metrics
print("\nSummary of statistical metrics:")
print(df.describe(include='all'))

Data:
      Name  Age  Gender  Score
0    Hafsa   12  female     12
1   Ayesha   23  female     23
2    ahmed   34    male     34
3  Malaika   34  female     34
4     noor   21  female     21
First few rows of the DataFrame:
      Name  Age  Gender  Score
0    Hafsa   12  female     12
1   Ayesha   23  female     23
2    ahmed   34    male     34
3  Malaika   34  female     34
4     noor   21  female     21

Data types of each column:
Name      object
Age        int64
Gender    object
Score      int64
dtype: object

Summary of statistical metrics:
         Name        Age  Gender      Score
count       5   5.000000       5   5.000000
unique      5        NaN       2        NaN
top     Hafsa        NaN  female        NaN
freq        1        NaN       4        NaN
mean      NaN  24.800000     NaN  24.800000
std       NaN   9.364828     NaN   9.364828
min       NaN  12.000000     NaN  12.000000
25%       NaN  21.000000     NaN  21.000000
50%       NaN  23.000000     NaN  23.000000
75%   

In [38]:

import pandas as pd
import numpy as np
#Q#7

# Create a DataFrame with 10 rows
# data = {
#     'ID': range(1, 11),
#     'Age': np.random.randint(18, 60, size=10),
#     'Income': np.random.randint(30000, 100000, size=10),
#     'Score': [np.nan, 75, 82, np.nan, 91, 88, np.nan, 77, 85, 90]
# }
# Create a DataFrame with 10 rows
data = {
    'ID': range(1, 11),
    'Age': [12, 23, 34, 34, 21, 12, 23, 34, 34, 21],
    'Income': [1222, 2343, 35554, 3235544, 2231, 12325, 2353, 353234, 343652, 236651],
    'Score': [np.nan, 75, 82, np.nan, 91, 88, np.nan, 77, 85, 90]
}

df = pd.DataFrame(data)

# Sort the DataFrame by 'Income' in descending order and create a copy
sorted_df = df.sort_values(by='Income', ascending=False).copy()

# Replace missing values in 'Score' with the average score of the column
average_score = sorted_df['Score'].mean()
sorted_df['Score'] = sorted_df['Score'].fillna(average_score)

# Print the sorted DataFrame and the average score
print("Sorted DataFrame by Income (descending):")
print(sorted_df)

print("\nAverage Score (used to replace missing values):", average_score)

#Q#8
# Filter rows where 'Income' > 50000 and 'Age' < 30
filtered_rows = df[(df['Income'] > 50000) & (df['Age'] < 30)]

# Retrieve only the 'ID' and 'Score' columns
result = filtered_rows[['ID', 'Score']]

# Print the results
print("\nFiltered Rows (Income > 50000 and Age < 30):")
print(result)

Sorted DataFrame by Income (descending):
   ID  Age   Income  Score
3   4   34  3235544   84.0
7   8   34   353234   77.0
8   9   34   343652   85.0
9  10   21   236651   90.0
2   3   34    35554   82.0
5   6   12    12325   88.0
6   7   23     2353   84.0
1   2   23     2343   75.0
4   5   21     2231   91.0
0   1   12     1222   84.0

Average Score (used to replace missing values): 84.0

Filtered Rows (Income > 50000 and Age < 30):
   ID  Score
9  10   90.0


In [32]:
#Q#9
import pandas as pd

# Create a DataFrame
data = {
    'Department': ['HR', 'Finance', 'IT', 'HR', 'Finance', 'IT', 'IT', 'HR', 'Finance', 'IT'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Judy'],
    'Salary': [60000, 70000, 80000, 62000, 72000, 75000, 85000, 64000, 71000, 90000],
    'Experience': [5, 6, 7, 5, 4, 3, 2, 6, 5, 8]
}

df = pd.DataFrame(data)

# Group by 'Department' and calculate mean and maximum Salary
salary_stats = df.groupby('Department')['Salary'].agg(['mean', 'max']).reset_index()

# Count the total number of employees in each department
employee_count = df['Department'].value_counts().reset_index()
employee_count.columns = ['Department', 'Total Employees']

# Combine the results
result = pd.merge(salary_stats, employee_count, on='Department')

# Print the results
print("Salary Statistics and Employee Count by Department:")
print(result)


Salary Statistics and Employee Count by Department:
  Department     mean    max  Total Employees
0    Finance  71000.0  72000                3
1         HR  62000.0  64000                3
2         IT  82500.0  90000                4


In [41]:
#QUESTION.10

import pandas as pd

df1 = pd.DataFrame({
    'Employee': ['HUMAILA', 'Basit', 'hafsa', 'Dawood', 'Ayesha'],
    'Department': ['HR', 'Engineering', 'Marketing', 'Engineering', 'HR'],
    'Salary': [70000, 90000, 50000, 80000, 60000]
})

df2 = pd.DataFrame({
    'Employee': ['HUMAILA', 'Basit', 'hafsa', 'Dawood', 'Ayesha'],
    'Project': ['Project1', 'Project2', 'Project1', 'Project3', 'Project2']
})

mer_df = pd.merge(df1, df2, on='Employee', how='inner')

tot_sal = mer_df.groupby('Project')['Salary'].sum()
print("DataFrame1:")
print(df1)
print("DataFrame2:")

print(df2)
print("Merged DataFrame:")
print(mer_df)
print("Total Salary for each Project:")
print(tot_sal)

DataFrame1:
  Employee   Department  Salary
0  HUMAILA           HR   70000
1    Basit  Engineering   90000
2    hafsa    Marketing   50000
3   Dawood  Engineering   80000
4   Ayesha           HR   60000
DataFrame2:
  Employee   Project
0  HUMAILA  Project1
1    Basit  Project2
2    hafsa  Project1
3   Dawood  Project3
4   Ayesha  Project2
Merged DataFrame:
  Employee   Department  Salary   Project
0  HUMAILA           HR   70000  Project1
1    Basit  Engineering   90000  Project2
2    hafsa    Marketing   50000  Project1
3   Dawood  Engineering   80000  Project3
4   Ayesha           HR   60000  Project2
Total Salary for each Project:
Project
Project1    120000
Project2    150000
Project3     80000
Name: Salary, dtype: int64
